### ISSUE TITLE
PiCamera

### ISSUE THREAD

**Issue by theyosh** [alec-pinson/TerrariumPI#16]
PiCamera is not working in Docker. The python libs are installed, but the hardware is not available.

More info:
https://www.losant.com/blog/how-to-access-the-raspberry-pi-camera-in-docker

As far I can judge, we need `--device /dev/vchiq` to the docker call.
mount `/opt/vc` from the Raspberry PI
And add an environment setting `--env LD_LIBRARY_PATH=/opt/vc/lib`

And then I need the folder `/opt/vc/bin/` to the env bin path, as I need the application `raspivid` and `raspistill` to get data from the RPICam.

**Comment by theyosh** [comment]
And this is now blocking my startup. As I am testing with the same setup as my develop system. So, if possible, could this be addressed first? :)

**Comment by alec-pinson** [comment]
First try update your `docker-compose.yaml` to:

```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-14
    volumes:
      - /terrariumpi-logs:/TerrariumPI/logs
      - /terrariumpi-data:/TerrariumPI/data
      - /terrariumpi-media:/TerrariumPI/media
      - /terrariumpi-DenkoviRelayCommandLineTool:/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
      - /opt/vc/bin:/opt/vc/bin
    network_mode: host
    restart: always
    privileged: true
    environment:
      TZ: "Europe/Amsterdam"
```

then run `docker-compose up -d` again and it should re-create the container

**Comment by alec-pinson** [comment]
If that doesn't work try this

```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-14
    volumes:
      - /terrariumpi-logs:/TerrariumPI/logs
      - /terrariumpi-data:/TerrariumPI/data
      - /terrariumpi-media:/TerrariumPI/media
      - /terrariumpi-DenkoviRelayCommandLineTool:/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
      - /opt/vc/bin:/opt/vc/bin
    network_mode: host
    restart: always
    privileged: true
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      TZ: "Europe/Amsterdam"
```

If this works we can add the `LD_LIBRARY_PATH` environment variable into Dockerfile instead so nobody needs to worry about it
