### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#21]
Some documentation and also `install.sh` may need to be updated for the following:-

- [x] location of calendar has changed to `data/calendar.ics`
- [x] location of database has changed to `data/terrariumpi.db`
- [x] location of custom logging config has changed to `log/logging.custom.cfg`
- [x] instructions on how to set timezone within docker-compose.yaml + list of timezones
- [x] instructions on how to use DenkoviRelayCommandLineTool with docker
- [ ] instructions on how to use docker & docker-compose

**Comment by theyosh** [comment]
There is now a `docker-compose.yaml` file in the repository, but should that not be renamed to `docker-compose.yaml.example` so that you can make you own setup in the docker compose file. And that we ignore that file. So it will not be overwritten when the example is changing due to software updates.

**Comment by theyosh** [comment]
Also, as the volumes do increase, maybe we can also reorder them. 
```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-18
    volumes:
      - /opt/terrariumpi/logs:/TerrariumPI/log
      - /opt/terrariumpi/data:/TerrariumPI/data
      - /opt/terrariumpi/media:/TerrariumPI/media
      - /opt/terrariumpi/webcam-archive:/TerrariumPI/webcam/archive
      - /opt/terrariumpi/DenkoviRelayCommandLineTool:/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
      - /opt/vc/bin:/opt/vc/bin
      - /dev:/dev
```

So that all the volumes for TP are at `/opt/terrariumpi/` . To me, it looks a bit more organized and neater...

**Comment by alec-pinson** [comment]
much much nicer, included in this pr
- https://github.com/alec-pinson/TerrariumPI/pull/24

**Comment by theyosh** [comment]
I need a brake. Will be back in 1 or 2 hours.

**Comment by alec-pinson** [comment]
> I need a brake. Will be back in 1 or 2 hours.

haha you are pretty hardcore with this, what time did you even goto sleep last night 😆

**Comment by theyosh** [comment]
Yeah, I do sleep, but 7 hours is enough for me. So I updated the install.sh file so it will move the files to the new locations.

**Comment by theyosh** [comment]
Update website: https://theyosh.github.io/TerrariumPI/hardware/relay/energenie-usb/#outdated-software , https://theyosh.github.io/TerrariumPI/hardware/relay/denkovi-v2/#installation , https://theyosh.github.io/TerrariumPI/install/#docker

This is a first attempt. For now it is enough. It will need some fine tuning.

But there should also a Docker paragraph in the README file

**Comment by alec-pinson** [comment]
Looks good, you'll need to update the docs though with this if it fixes the kill/stop stuff

```yaml
    volumes:
      - /opt/terrariumpi/logs:/TerrariumPI/log
      - /opt/terrariumpi/data:/TerrariumPI/data
      - /opt/terrariumpi/media:/TerrariumPI/media
      - /opt/terrariumpi/webcam-archive:/TerrariumPI/webcam/archive
      - /opt/terrariumpi/DenkoviRelayCommandLineTool:/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
      - /opt/vc/bin:/opt/vc/bin
      - /dev:/dev
    network_mode: host
    restart: always
    privileged: true
    stop_grace_period: 1m
    stop_signal: SIGINT
    environment:
      TZ: "Europe/Amsterdam" # timezone list can be found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      ENABLE_I2C: "true"
      ENABLE_1_WIRE: "true"
      ENABLE_CAMERA: "true"
      ENABLE_SERIAL: "true"
      ENABLE_CO2_SENSORS: "true"
      AUTO_REBOOT: "true"
```
