### ISSUE TITLE
support for timezone configuration

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#6]
## As per this https://github.com/theyosh/TerrariumPI/pull/626#issuecomment-967460773

> And how is the correct timezone configured? Is that depending on the host or can the container run in its own timezone? Here https://github.com/theyosh/TerrariumPI/blob/4.x.y.z/install.sh#L74 I force the user to select the correct timezone so that I can convert date and time to the correct timezone of the user.

**Comment by alec-pinson** [comment]
Ahh I missed this, I will look into it further but I'm hoping it will be something simple like updating:-

```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-10
    volumes:
      - /terrariumpi-logs:/TerrariumPI/logs
      - /terrariumpi-data:/TerrariumPI/data
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
    network_mode: host
    restart: always
    privileged: true
    environment:
      TIMEZONE=XYZ
```

**Comment by theyosh** [comment]
Euh, that is an option. The correct timeszone information is stored at: `/etc/timezone` with the contents: `Europe/Amsterdam`

But, it looks not that hard: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container

**Comment by alec-pinson** [comment]
That worked 👍  tested with Africa

```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-10
    volumes:
      - /terrariumpi-logs:/TerrariumPI/logs
      - /terrariumpi-data:/TerrariumPI/data
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
    network_mode: host
    restart: always
    privileged: true
    environment:
      TZ: "Africa/Lusaka"
```

```
alec@terrarium-pi:~$ docker exec -it alec_terrariumpi_1 date
Sat Nov 13 17:23:21 CAT 2021
```

Will need to include this in the documentation also

- [ ] document timezones within docker
