### ISSUE TITLE
look into DenkoviRelayCommandLineTool setup/license

### ISSUE THREAD

**Issue by alec-pinson** [alec-pinson/TerrariumPI#9]
## As per this https://github.com/theyosh/TerrariumPI/pull/626#issuecomment-967460773

> And there are some people using: https://github.com/theyosh/TerrariumPI/tree/4.x.y.z/3rdparty/DenkoviRelayCommandLineTool But I guess just adding a volume is not enough. Because a volume cannot have this readme inside it during install. It needs to be clean the first time you add/create a volume? Or is there a trick....

**Comment by alec-pinson** [comment]
Hmm this one sounds complicated due to licensing? I will look into this one more when I have some time

**Comment by theyosh** [comment]
Because of the license of Denkovi, I am not allowed to pack their software with mine. So I have to tell people where they can download it, and how to use it.

So, it is free to use, but you have to install it manually. The owner of the device so the speak.

But, then I thought this. What if, we just make a new volume, on the path: `/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool/` and clear that folder when the copy the source. So in the https://github.com/alec-pinson/TerrariumPI/blob/4.x.y.z-docker/Dockerfile#L40 part, we can clear the folder and make the volume work.

The readme is only needed on Github self, so people can read it, and know what to do. That the readme file is not on the docker image, is not a problem for me.
Then two issues remain.

1. It needs Java runtime. It is a java application.
2. How can someone add this to a docker image afterwards. How to get the files in a Docker volume manually.

And then another strange idea... is it an idea, that this will be a different docker image, because it needs java. And that we can combine docker images somehow. I have seen single programs in a docker. So maybe that is something we can do?

**Comment by alec-pinson** [comment]
There's a few options

## 1. we could release 2 versions of the docker image e.g:

`4.0.0-java` - which has `openjdk-11-jre-headless` pre-installed
`4.0.0` - comes without java

The only reason to separate them would be to keep the docker image smaller.
So basically if someone wanted to use `DenkoviRelayCommandLineTool` they would use the java version.

Then like you say we can easily add an option for a mount point to the Pi OS something like:
```
/terrariumpi-DenkoviRelayCommandLineTool:/TerrariumPI/3rdparty/DenkoviRelayCommandLineTool
```
or maybe to allow support for any future 3rd party addons something like:
```
/terrariumpi-addons:/TerrariumPI/addons
```

but basically it would mean that a user would download the .jar and put it in `/terrariumpi-DenkoviRelayCommandLineTool` or `/terrariumpi-addons` on their Raspberry Pi and that's it.

## 2. Separate image/container
It is also possible to have a completely separate image/container for this but I think that's a bit more complicated when it comes to attempting to communicate with the other container to run the commands, you would probably need some wrapper to make it work.

```yaml
version: "3.3"
services:
  terrariumpi:
    image: wkd1/test:new-slim-10
    volumes:
      - /terrariumpi-logs:/TerrariumPI/logs
      - /terrariumpi-data:/TerrariumPI/data
      - /boot/config.txt:/boot/config.txt
      - /boot/cmdline.txt:/boot/cmdline.txt
      - /etc/modules:/etc/modules
    network_mode: host
    restart: always
    privileged: true
    environment:
      TZ: "Africa/Lusaka"
DenkoviRelayCLI:
    image: java/some-ready-made-image:1.0.0
    volumes:
      - /terrariumpi-DenkoviRelayCommandLineTool:/app
```

---

I think option 1. is probably the easiest/best option.
If we could package `DenkoviRelayCLI` in a docker image then there would be a 3rd option which would be a big improvement on option 2. However if we cannot package it due to licensing then this kinda blocks that too I think
